### ISSUE TITLE
[Bug]:  Windows version doesn't recognize Active Stylus

### ISSUE THREAD

**Issue by mate282** [LinwoodDev/Butterfly#697] opened 2024-05-12 09:29 UTC
### What happened?

I've tried both stable and nightly versions but none seems to support active stylus. In the settings menu if I touch the test area with Pen or finger both are detected as touch. 
In the web version no problem, it correctly dectects stylus with the two action buttons (eraser and selection) but it's really slow (I've tried it on Edge).

PS: If you have any suggestions on how to make the web version faster I would be grateful.

### Version

2.1.0+104

### Platform

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment] 2024-05-12 10:00
sadly a duplicate of #238. I can't do anything about it, we need to wait until it's fixed on the flutter side.

**Closed by CodeDoctorDE** 2024-05-12 10:00 UTC
Labels: bug
