### ISSUE TITLE
[Bug]: Crashes on Z Fold 3 when holding side button of S Pen (Fold Edition)

### ISSUE THREAD

**Issue by pdtheowl** [LinwoodDev/Butterfly#289] opened 2022-09-24 13:59 UTC
### What happened?

I was trying to see if the program had the feature in which holding down the side button of the S Pen turns it into an erasor, but when I tapped the screen with the S Pen while holding the side button, the app crashed.

Hardware involved
Samsung Galaxy Z Fold 3
S Pen (Fold Edition)

### Version

1.4.4

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment] 2022-09-24 19:20
Hmm, I currently have no android device which supports stylus input. I will investigate it further

**Comment by CodeDoctorDE** [comment] 2022-09-29 09:19
I updated the dependencies and found a bug in flutter: https://github.com/flutter/flutter/issues/110671

Can you try uninstalling the latest version and test this one (please note that after uninstalling all files are gone): https://github.com/LinwoodCloud/Butterfly/suites/8529088561/artifacts/380353581

**Comment by CodeDoctorDE** [comment] 2022-10-01 09:48
Bug confirmed. I will investigate it further

**Comment by CodeDoctorDE** [comment] 2022-10-01 09:56
It's a bug from flutter: https://github.com/flutter/flutter/issues/111068. We need to wait until they will fix it.

**Comment by pdtheowl** [comment] 2022-10-03 14:27
Gotcha, also haven't been able to go any testing on my end due to having
broken my S pen tip and not being able to find the replacements.

Phatanoune Douangvilay (Pd, She/Her/They)

**Comment by pdtheowl** [comment] 2022-10-11 08:11
Feel free to let me know if you need any help testing, I also have a Galaxy
Note 9 that I can try it on! And im sure the Note9 and Galaxy Fold reddit
would be willing to help :)

**Comment by CodeDoctorDE** [comment] 2022-10-11 08:14
The problem is that I can't fix the error. It needs to be fixed by the Flutter team.
Thanks anyway!

**Comment by CodeDoctorDE** [comment] 2023-05-17 08:47
The crash should be fixed in the new 2.0 alphas but does not detect as a stylus device. Please follow [this issue](https://github.com/flutter/flutter/issues/42846) for this

**Closed by CodeDoctorDE** 2023-05-17 08:47 UTC
Labels: confirmed, external
