### ISSUE TITLE
[Bug]: Flatpak install says "nightly" when I install latest stable

### ISSUE THREAD

**Issue by markwmuller** [LinwoodDev/Butterfly#570] opened 2024-01-15 00:36 UTC
### What happened?

Installing Butterfly via flatpak (https://flathub.org/apps/dev.linwood.butterfly) gives me version 2.0.0, but the banner at the top says "Butterfly Nightly". I'm guessing there's a mixup somewhere. 

![image](https://github.com/LinwoodDev/Butterfly/assets/3056063/f3edcf06-42f2-4942-b29e-ac9f03e83865)

![image](https://github.com/LinwoodDev/Butterfly/assets/3056063/94f6d83a-76ec-42dd-8ccc-923270fdaaa6)

I'm using Ubuntu 22.04. 

### Version

2.0.0

### Platform

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment] 2024-01-15 08:27
Thanks for reporting. The bug shouldn't be too critical, with the nightly version you can try out the collaboration feature

**Comment by CodeDoctorDE** [comment] 2024-01-15 08:53
Fixed in 2.0.1

**Comment by CodeDoctorDE** [comment] 2024-01-15 09:55
Reopened because it didn't fix the problem

**Comment by CodeDoctorDE** [comment] 2024-02-01 11:08
Yeah, the problem is:
The check for nightly is wrong: https://github.com/LinwoodDev/Butterfly/blob/da8ed04432b84810dcc0eb9b63023ffb79c8aad1/.github/workflows/build.yml#L160

The github.event_name is "push" and we don't get the information if the running job is inside a prerelease or not

**Comment by CodeDoctorDE** [comment] 2024-11-10 12:22
fixed

**Closed by CodeDoctorDE** 2024-11-10 12:22 UTC
Labels: bug, good first issue, confirmed, ci
