### ISSUE TITLE
[Bug]: Unable to export to .svg on android 

### ISSUE THREAD

**Issue by Zachary-Luckman** [LinwoodDev/Butterfly#585] opened 2024-02-06 11:43 UTC
### What happened?

Device : Samsung Galaxy tab A 2018
Version : Android 10

When trying to export a drawing to .svg on android. The window pops up but when clicking the export button, nothing happens. For comparison, when exporting to an image file. The window pops up and when the export button is clicked it shows where you want to share the image file. 

### Version

2.02

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment] 2024-02-06 11:46
thanks for reporting this bug. bug is reproducable in the latest nightly 2.0.3-rc.0 on android.
web and windows works fine, looks like a bug in the android specific file saving

**Comment by CodeDoctorDE** [comment] 2024-02-07 16:27
Fixed in 2.0.3-rc.1

**Closed** 2024-02-07 16:27 UTC
Labels: bug, confirmed

**Comment by HusniMuhammad** [comment] 2024-02-11 13:42
> Fixed in 2.0.3-rc.1

Where is saves svg files (path)

**Comment by CodeDoctorDE** [comment] 2024-02-11 16:17
2.0.3-rc.1 isn't released currently, will be released next monday.
It will open a share dialog to save it

**Comment by HusniMuhammad** [comment] 2024-02-12 07:52
> thanks for reporting this bug. bug is reproducable in the latest nightly 2.0.3-rc.0 on android. web and windows works fine, looks like a bug in the android specific file saving

I think also svg importing not working in Android?

**Comment by CodeDoctorDE** [comment] 2024-02-12 08:34
SVG importing works fine for me. After importing you need to click where you want to set the image

**Comment by HusniMuhammad** [comment] 2024-02-12 08:36
> SVG importing works fine for me. After importing you need to click where you want to set the image
Trying again

**Comment by HusniMuhammad** [comment] 2024-02-12 08:44
> SVG importing works fine for me. After importing you need to click where you want to set the image

Worked
