### ISSUE TITLE
[Bug]: Add option to change data directory on android

### ISSUE THREAD

**Issue by jhc86** [LinwoodDev/Butterfly#569] opened 2024-01-09 20:51 UTC
### What happened?

When adding a default local connection, I exit the app and then start it to receive this message:
FileSystemException: Creation failed, path = 'content:' (OS Error: Read-only file system, errno = 30

I also cannot seem to save anything to the connection.

Path:
content://com.android.externalstorage.documents/tree/primary%3AButterfly

Same result on two Android systems:
GrapheneOS (Android 14)
Samsung Galaxy S21 FE 5G (Android 13)

### Version

2.0.1-rc.0

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment] 2024-01-10 07:52
Bug confirmed. I will look at it

**Comment by CodeDoctorDE** [comment] 2024-01-10 09:29
Hmm,
I use the file_selector package that uses the OPEN_DIR intent to access the folder.
Seems like the new android 11 storage system does not work good with it...
If anyone wants to help feel free to make a pull request

**Comment by CodeDoctorDE** [comment] 2024-01-10 10:21
I researched a bit and the problem is:
the getDirectoryPath function gives me a content uri instead of a path and dart cannot work with uris and only with paths.
But I have currently no solution how to fix this. if anyone has more information regarding this, feel free to add a comment here

**Comment by CodeDoctorDE** [comment] 2024-01-29 18:04
I created an issue on the flutter repository: https://github.com/flutter/flutter/issues/141250.
After this is closed I will reenable this feature in the android version

**Comment by CodeDoctorDE** [comment] 2024-04-30 06:09
The time has come...
The issue was closed in the library.
I will reenable this feature for android in the 2.1.0-rc.1 update 🎉

**Comment by CodeDoctorDE** [comment] 2024-05-01 08:17
Fixed in 2.1.0-rc.1

**Comment by DDzwiedziu** [comment] 2024-09-13 10:59
I found that this is not working in both stable (Android 12 and 14) and nightly (Android 12). Changing the path makes still the bottom text of the option say "default path", and files are not saved in the new directory (in the nightly they're not saved at all, even naming the file disappears after confirming).

**Comment by CodeDoctorDE** [comment] 2024-09-13 13:10
Thanks for reporting I will tru to fix it

**Comment by CodeDoctorDE** [comment] 2024-09-13 17:12
Fixed, will land in 2.2.0-rc.0

**Comment by DDzwiedziu** [comment] 2024-10-06 09:06
If this landed now in 2.2.0, then this does not seem to work. The label still reads "Default Path" and the files are still from the default location.

**Comment by CodeDoctorDE** [comment] 2024-10-06 09:18
Hmm, I tested it on my linux machine and thought this could also fix the android bug. I will investigate it further

**Comment by DDzwiedziu** [comment] 2024-10-06 09:26
I can only confirm that this affect Android 12 and 14. Tried to select the directory again on both devices, but it did not change the location.

**Comment by CodeDoctorDE** [comment] 2024-10-10 08:22
can you try opening it in the latest nightly? You can go into the play store and enter the beta program. I tested it on my s24+ with android 14 and it works nicely when selecting a subfolder of the documents directory

**Comment by DDzwiedziu** [comment] 2024-10-10 10:00
Would the F-Droid nightly be okay (when it's updated there)?

**Comment by CodeDoctorDE** [comment] 2024-10-10 10:01
yeah it's the same version, you only need to see if it's 2.0.1-rc.0

**Comment by CodeDoctorDE** [comment] 2024-10-10 10:04
Oh wait, I think i also fixed it again in the develop branch and didn't released it just yet. I will notify you if i release the new version

**Comment by CodeDoctorDE** [comment] 2024-10-17 09:03
should be fixed in 2.2.1 and 2.2.1-rc.1

**Closed by CodeDoctorDE** 2024-10-17 09:03 UTC
Labels: bug, confirmed, external

**Comment by DDzwiedziu** [comment] 2024-12-22 12:20
2.2.3-rc.1

https://github.com/user-attachments/assets/279790b1-165a-4d89-9f7d-68a2ed9078d5

**Comment by CodeDoctorDE** [comment] 2024-12-22 12:25
Hmm I really don't know why this happens, on my device it works correctly. Which android version do you use?

**Comment by DDzwiedziu** [comment] 2024-12-22 19:11
I've tried 11, 12, and 14. Both stable and nightly.

**Comment by CodeDoctorDE** [comment] 2025-11-13 07:46
thanks for reporting this, this is because of the new file picker i use.
need to see what i can do
