### ISSUE TITLE
[Bug]: Pen gets recognized as mouse

### ISSUE THREAD

**Issue by JanSchKC** [LinwoodDev/Butterfly#581] opened 2024-02-02 17:14 UTC
### What happened?

Hello,
I use a Lenovo Thinkpad Pen Pro 2 which was included in my laptop (X380 Yoga). It works, but it seems like it is recognized as a mouse because when writing, the cross is always on the screen and when I enable Pen only mode, my pen isnt getting recognized. As a result, there is also no pressure sensitivity. 

Another problem is that only one button seems to work. I tested it on a website you posted in an earlier bug report. The second button (3) seems to work, but there is no reaction when pressing the other one. This button is the one used as eraser in other programs.

I didnt have this problem on any other handwritten notes program.
Thanks in advance!

### Version

2.0.2

### Platform

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment] 2024-02-02 17:18
Sadly a duplicate of #238. Sorry, I can't do anything about it, it needs to be fixed on the flutter side.

**Closed** 2024-02-02 17:19 UTC
Labels: bug, duplicate

**Comment by JanSchKC** [comment] 2024-02-02 17:24
okay, thanks anyway!
